#!/bin/sh

#intialize to 0 to be sure we do not try to run if there are no
#zram devices
NUM_ZRAM_DEV=0

#get number of zram devices from kernel command line
CMDLINE=`cat /proc/cmdline`
for x in $CMDLINE; do
        if test "${x%%=*}" = zram.num_devices; then
                NUM_ZRAM_DEV="${x#zram.num_devices=}"
        fi
done

if [ $NUM_ZRAM_DEV -eq 0 ]; then
        exit 0
fi

MEMORY_IN_KBYTES=" `cat /proc/meminfo | grep MemTotal | awk '{ print $2 }'`"

SIZE=$(( $MEMORY_IN_KBYTES * 1024 * 20 / 100 / NUM_ZRAM_DEV ))


num=0
while [ "$num" -lt "$NUM_ZRAM_DEV" ]; do
        echo $SIZE > /sys/block/zram${num}/disksize
        /sbin/mkswap /dev/zram${num}
        num=$(($num+1))
done
